graph TD
    A[GET] --> D
    C[POST] --> D
    
   D[<b>Controller 类</b><br><code>BookController</code><br><code>FavoritesController</code><br><code>HomeController</code><br><code>UserController</code><br><code>UserProfileController</code>]
   D<-->E[<b>Service 类</b><br><code>BookService</code><br><code>FavoritesService</code><br><code>UserService</code><br><code>UserProfileService</code>]
   E<-->F[<b>Repository 类</b><br><code>BookRepository</code><br><code>FavoritesRepository</code><br><code>UserRepository</code><br><code>UserProfileRepository</code><br>……]

	subgraph 后端服务
	D
	E
	F
	end
    
    F <--> M[(MySQL)]
